with _0001 as (select * from {{ref('_1001_events_transform')}})

select distinct
    user_pseudo_id,
    session_id,
    max(case when lower(event_name) = 'payment_method' then 'payment_method' else ',' end) as payment_method_triggered,
    max(case when lower(event_name) = 'inwisselen_per_mail' then 'inwisselen_per_mail' else ',' end) as inwisselen_per_mail_triggered,
    max(case when lower(event_name) = 'inwisselen_nochoice' then 'inwisselen_nochoice' else ',' end) as inwisselen_nochoice_triggered,
    max(case when lower(event_name) = 'inwisselen_beslis_ik_later' then 'inwisselen_beslis_ik_later' else ',' end) as inwisselen_beslis_ik_later_triggered,
    max(case when lower(event_name) = 'inwisselen_per_post' then 'inwisselen_per_post' else ',' end) as inwisselen_per_post_triggered,
    max(case when lower(event_name) = 'filter_use' then 'filter_use' else ',' end) as filter_use_triggered,
    max(case when lower(event_name) = 'top_navigation_use' then 'top_navigation_use' else ',' end) as top_navigation_use_triggered,
    max(case when lower(event_name) = 'mobile_navigation_use' then 'mobile_navigation_use' else ',' end) as mobile_navigation_use_triggered,
    max(case when lower(event_name) = 'sort_use' then 'sort_use' else ',' end) as sort_use_triggered,
    max(case when lower(event_name) = 'add_payment_info' then 'add_payment_info' else ',' end) as add_payment_info_triggered,
    max(case when lower(event_name) = 'add_shipping_info' then 'add_shipping_info' else ',' end) as add_shipping_info_triggered,
    max(case when lower(event_name) = 'add_to_cart' then 'add_to_cart' else ',' end) as add_to_cart_triggered,
    max(case when lower(event_name) = 'add_to_wishlist' then 'add_to_wishlist' else ',' end) as add_to_wishlist_triggered,
    max(case when lower(event_name) = 'begin_checkout' then 'begin_checkout' else ',' end) as begin_checkout_triggered,
    max(case when lower(event_name) = 'purchase' then 'purchase' else ',' end) as purchase_triggered,
    max(case when lower(event_name) = 'refund' then 'refund' else ',' end) as refund_triggered,
    max(case when lower(event_name) = 'remove_from_cart' then 'remove_from_cart' else ',' end) as remove_from_cart_triggered,
    max(case when lower(event_name) = 'select_item' then 'select_item' else ',' end) as select_item_triggered,
    max(case when lower(event_name) = 'select_promotion' then 'select_promotion' else ',' end) as select_promotion_triggered,
    max(case when lower(event_name) = 'view_cart' then 'view_cart' else ',' end) as view_cart_triggered,
    max(case when lower(event_name) = 'view_item' then 'view_item' else ',' end) as view_item_triggered,
    max(case when lower(event_name) = 'view_item_list' then 'view_item_list' else ',' end) as view_item_list_triggered,
    max(case when lower(event_name) = 'view_promotion' then 'view_promotion' else ',' end) as view_promotion_triggered,
    max(case when lower(event_name) = 'cro_event_1' then 'cro_event_1' else ',' end) as cro_event_1_triggered,
    max(case when lower(event_name) = 'cro_event_2' then 'cro_event_2' else ',' end) as cro_event_2_triggered,
    max(case when lower(event_name) = 'cro_event_3' then 'cro_event_3' else ',' end) as cro_event_3_triggered,
    max(case when lower(event_name) = 'cro_event_4' then 'cro_event_4' else ',' end) as cro_event_4_triggered,
    max(case when lower(event_name) = 'cro_event_5' then 'cro_event_5' else ',' end) as cro_event_5_triggered,
    max(case when lower(event_name) = 'cro_event_6' then 'cro_event_6' else ',' end) as cro_event_6_triggered,
    max(case when lower(event_name) = 'cro_event_7' then 'cro_event_7' else ',' end) as cro_event_7_triggered,
    max(case when lower(event_name) = 'cro_event_8' then 'cro_event_8' else ',' end) as cro_event_8_triggered,
    max(case when lower(event_name) = 'cro_event_9' then 'cro_event_9' else ',' end) as cro_event_9_triggered,
    max(case when lower(event_name) = 'cro_event_10' then 'cro_event_10' else ',' end) as cro_event_10_triggered,
    max(case when lower(event_name) = 'cro_event_11' then 'cro_event_11' else ',' end) as cro_event_11_triggered,
    max(case when lower(event_name) = 'cro_event_12' then 'cro_event_12' else ',' end) as cro_event_12_triggered,
    max(case when lower(event_name) = 'cro_event_13' then 'cro_event_13' else ',' end) as cro_event_13_triggered,
    max(case when lower(event_name) = 'cro_event_14' then 'cro_event_14' else ',' end) as cro_event_14_triggered,
    max(case when lower(event_name) = 'cro_event_15' then 'cro_event_15' else ',' end) as cro_event_15_triggered,
    max(case when lower(event_name) = 'cro_event_16' then 'cro_event_16' else ',' end) as cro_event_16_triggered,
    max(case when lower(event_name) = 'cro_event_17' then 'cro_event_17' else ',' end) as cro_event_17_triggered,
    max(case when lower(event_name) = 'cro_event_18' then 'cro_event_18' else ',' end) as cro_event_18_triggered,
    max(case when lower(event_name) = 'cro_event_19' then 'cro_event_19' else ',' end) as cro_event_19_triggered,
    max(case when lower(event_name) = 'cro_event_20' then 'cro_event_20' else ',' end) as cro_event_20_triggered,
    max(case when lower(event_name) = 'view_item' then 'PDP' else ',' end) as PDP_seen,
    max(case when lower(event_name) = 'view_item_list' then 'PLP' else ',' end) as collection_page_seen,    
from _0001
group by user_pseudo_id, session_id