with _1000 as (
    select * from {{ref('_1000_users')}}
    where experiment_name is not null and event_category != 'other events'
)

select
    min(event_date) as min_date,
    max(event_date) as max_date,
    experiment_name as experiments, 
    variant_name as variants,
    device,
    event_name,
    count(distinct transaction_id) as purchases,
    sum(revenue) as revenue,
    count(distinct user_pseudo_id) as users,
    count(distinct session_id) as sessions,
    -- sum(case when payment_method_triggered !=',' then 1 else 0 end) as payment_method_triggered,
    -- sum(case when inwisselen_per_mail_triggered !=',' then 1 else 0 end) as inwisselen_per_mail_triggered,
    -- sum(case when inwisselen_nochoice_triggered !=',' then 1 else 0 end) as inwisselen_nochoice_triggered,
    -- sum(case when inwisselen_beslis_ik_later_triggered !=',' then 1 else 0 end) as inwisselen_beslis_ik_later_triggered,
    -- sum(case when inwisselen_per_post_triggered !=',' then 1 else 0 end) as inwisselen_per_post_triggered,
    -- sum(case when filter_use_triggered !=',' then 1 else 0 end) as filter_use_triggered,
    -- sum(case when top_navigation_use_triggered !=',' then 1 else 0 end) as top_navigation_use_triggered,
    -- sum(case when mobile_navigation_use_triggered !=',' then 1 else 0 end) as mobile_navigation_use_triggered,
    -- sum(case when sort_use_triggered !=',' then 1 else 0 end) as sort_use_triggered,
    -- sum(case when add_payment_info_triggered !=',' then 1 else 0 end) as add_payment_info_triggered,
    -- sum(case when add_shipping_info_triggered !=',' then 1 else 0 end) as add_shipping_info_triggered,
    -- sum(case when add_to_cart_triggered !=',' then 1 else 0 end) as add_to_cart_triggered,
    -- sum(case when add_to_wishlist_triggered !=',' then 1 else 0 end) as add_to_wishlist_triggered,
    -- sum(case when begin_checkout_triggered !=',' then 1 else 0 end) as begin_checkout_triggered,
    -- sum(case when purchase_triggered !=',' then 1 else 0 end) as purchase_triggered,
    -- sum(case when refund_triggered !=',' then 1 else 0 end) as refund_triggered,
    -- sum(case when remove_from_cart_triggered !=',' then 1 else 0 end) as remove_from_cart_triggered,
    -- sum(case when select_item_triggered !=',' then 1 else 0 end) as select_item_triggered,
    -- sum(case when select_promotion_triggered !=',' then 1 else 0 end) as select_promotion_triggered,
    -- sum(case when view_cart_triggered !=',' then 1 else 0 end) as view_cart_triggered,
    -- sum(case when view_item_triggered !=',' then 1 else 0 end) as view_item_triggered,
    -- sum(case when view_item_list_triggered !=',' then 1 else 0 end) as view_item_list_triggered,
    -- sum(case when view_promotion_triggered !=',' then 1 else 0 end) as view_promotion_triggered,
    -- sum(case when cro_event_1_triggered !=',' then 1 else 0 end) as cro_event_1_triggered,
    -- sum(case when cro_event_2_triggered !=',' then 1 else 0 end) as cro_event_2_triggered,
    -- sum(case when cro_event_3_triggered !=',' then 1 else 0 end) as cro_event_3_triggered,
    -- sum(case when cro_event_4_triggered !=',' then 1 else 0 end) as cro_event_4_triggered,
    -- sum(case when cro_event_5_triggered !=',' then 1 else 0 end) as cro_event_5_triggered,
    -- sum(case when cro_event_6_triggered !=',' then 1 else 0 end) as cro_event_6_triggered,
    -- sum(case when cro_event_7_triggered !=',' then 1 else 0 end) as cro_event_7_triggered,
    -- sum(case when cro_event_8_triggered !=',' then 1 else 0 end) as cro_event_8_triggered,
    -- sum(case when cro_event_9_triggered !=',' then 1 else 0 end) as cro_event_9_triggered,
    -- sum(case when cro_event_10_triggered !=',' then 1 else 0 end) as cro_event_10_triggered,
    -- sum(case when cro_event_11_triggered !=',' then 1 else 0 end) as cro_event_11_triggered,
    -- sum(case when cro_event_12_triggered !=',' then 1 else 0 end) as cro_event_12_triggered,
    -- sum(case when cro_event_13_triggered !=',' then 1 else 0 end) as cro_event_13_triggered,
    -- sum(case when cro_event_14_triggered !=',' then 1 else 0 end) as cro_event_14_triggered,
    -- sum(case when cro_event_15_triggered !=',' then 1 else 0 end) as cro_event_15_triggered,
    -- sum(case when cro_event_16_triggered !=',' then 1 else 0 end) as cro_event_16_triggered,
    -- sum(case when cro_event_17_triggered !=',' then 1 else 0 end) as cro_event_17_triggered,
    -- sum(case when cro_event_18_triggered !=',' then 1 else 0 end) as cro_event_18_triggered,
    -- sum(case when cro_event_19_triggered !=',' then 1 else 0 end) as cro_event_19_triggered,
    -- sum(case when cro_event_20_triggered !=',' then 1 else 0 end) as cro_event_20_triggered,

from _1000
group by experiment_name, variant_name, device, event_name
